version: '3.8'

services:
  cloudflared-ha:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token "TOKEN"
    networks:
      - tunnel
    restart: unless-stopped
networks:
  tunnel:
